dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
  
# command to install dependencies
install:
  - pip install codecov
  - pip install pillow
  - pip install scipy
  
# command to run tests
script: cd test && coverage run test.py